/**
 * leaseAgreement.ts
 * Client-side PDF generation for lease agreements using jsPDF + jspdf-autotable.
 * Call generateLeaseAgreementPDF(booking) with a fully-populated Booking object.
 */

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { Booking, Orchard, User } from '@/types';
import { formatDate, formatCurrency, titleCase } from '@/lib/format';

/* ─── colour palette ─── */
const FOREST    = [42, 78, 32]   as [number, number, number]; // #2a4e20
const CREAM_BG  = [252, 249, 242] as [number, number, number]; // #fcf9f2
const SAND      = [214, 204, 186] as [number, number, number]; // #d6ccba
const INK       = [28, 30, 27]   as [number, number, number]; // #1c1e1b
const SUB_TEXT  = [100, 108, 95] as [number, number, number]; // #646c5f
const WHITE     = [255, 255, 255] as [number, number, number];
const LIGHT_GRN = [230, 240, 225] as [number, number, number]; // table header bg

/* ─── helpers ─── */
const pageW  = 210; // A4 mm
const pageH  = 297;
const margin = 18;
const colW   = (pageW - margin * 2) / 2 - 4;

function labelVal(
  doc: jsPDF,
  x: number,
  y: number,
  label: string,
  value: string,
  maxWidth = colW
): number {
  doc.setFontSize(7.5).setTextColor(...SUB_TEXT).setFont('helvetica', 'normal');
  doc.text(label.toUpperCase(), x, y);
  doc.setFontSize(9.5).setTextColor(...INK).setFont('helvetica', 'normal');
  const lines = doc.splitTextToSize(value || '—', maxWidth);
  doc.text(lines, x, y + 4.5);
  return y + 4.5 + lines.length * 4.5;
}

function sectionHeader(doc: jsPDF, y: number, title: string): number {
  doc.setFillColor(...FOREST);
  doc.roundedRect(margin, y, pageW - margin * 2, 7.5, 1.5, 1.5, 'F');
  doc.setFontSize(9).setFont('helvetica', 'bold').setTextColor(...WHITE);
  doc.text(title, margin + 4, y + 5.2);
  return y + 7.5 + 5; // return next y
}

function hRule(doc: jsPDF, y: number): void {
  doc.setDrawColor(...SAND);
  doc.setLineWidth(0.3);
  doc.line(margin, y, pageW - margin, y);
}

function addFooter(doc: jsPDF, pageNum: number, totalPages: number): void {
  const y = pageH - 11;
  hRule(doc, y - 2);
  doc.setFontSize(7).setFont('helvetica', 'italic').setTextColor(...SUB_TEXT);
  doc.text(
    'This document is auto-generated by OrchardLease. It does not constitute legal advice.',
    margin,
    y + 2
  );
  doc.setFont('helvetica', 'normal');
  doc.text(`Page ${pageNum} of ${totalPages}`, pageW - margin, y + 2, { align: 'right' });
}

/* ─── main export ─── */
export function generateLeaseAgreementPDF(booking: Booking): void {
  const orchard = booking.orchardId as Orchard;
  const renter  = booking.renterId  as User;
  const seller  = booking.sellerId  as User;

  const doc = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'portrait' });

  /* ══ PAGE 1 ══════════════════════════════════════════════════════════ */

  /* ── header banner ─────────────────────────────────────────────────── */
  doc.setFillColor(...FOREST);
  doc.rect(0, 0, pageW, 38, 'F');

  // Logo / brand text
  doc.setFontSize(20).setFont('helvetica', 'bold').setTextColor(...WHITE);
  doc.text('OrchardLease', margin, 16);

  doc.setFontSize(9).setFont('helvetica', 'normal').setTextColor(200, 220, 190);
  doc.text('Intelligent Orchard Rental Marketplace', margin, 22);

  // Agreement title on the right
  doc.setFontSize(11).setFont('helvetica', 'bold').setTextColor(...WHITE);
  doc.text('LEASE AGREEMENT', pageW - margin, 14, { align: 'right' });

  doc.setFontSize(7.5).setFont('helvetica', 'normal').setTextColor(200, 220, 190);
  doc.text(`Ref: ${booking._id}`, pageW - margin, 20, { align: 'right' });
  doc.text(`Generated: ${new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}`, pageW - margin, 25.5, { align: 'right' });

  // Status badge
  const statusColor: [number, number, number] =
    booking.bookingStatus === 'approved'  ? [42, 120, 50] :
    booking.bookingStatus === 'completed' ? [60, 100, 180] : FOREST;
  doc.setFillColor(...statusColor);
  doc.roundedRect(pageW - margin - 28, 27.5, 28, 7, 2, 2, 'F');
  doc.setFontSize(7.5).setFont('helvetica', 'bold').setTextColor(...WHITE);
  doc.text(booking.bookingStatus.toUpperCase(), pageW - margin - 14, 32.5, { align: 'center' });

  /* ── cream background for body ──────────────────────────────────────── */
  doc.setFillColor(...CREAM_BG);
  doc.rect(0, 38, pageW, pageH - 38, 'F');

  let y = 48;

  /* ── SECTION 1: Parties ─────────────────────────────────────────────── */
  y = sectionHeader(doc, y, '1.  PARTIES TO THIS AGREEMENT');

  // Two-column grid for Owner | Lessee
  const col1 = margin + 2;
  const col2 = margin + colW + 10;

  // Column headers
  doc.setFontSize(8).setFont('helvetica', 'bold').setTextColor(...FOREST);
  doc.text('OWNER (LESSOR)', col1, y);
  doc.text('LESSEE (RENTER)', col2, y);
  y += 2;
  hRule(doc, y);
  y += 4;

  const rowStart = y;
  let y1 = y;
  let y2 = y;
  y1 = labelVal(doc, col1, y1, 'Full Name',     seller?.name  || '—');
  y1 = labelVal(doc, col1, y1 + 2, 'Email Address', seller?.email || '—');
  y1 = labelVal(doc, col1, y1 + 2, 'Phone Number',  seller?.phone || '—');

  y2 = labelVal(doc, col2, y2, 'Full Name',     renter?.name  || '—');
  y2 = labelVal(doc, col2, y2 + 2, 'Email Address', renter?.email || '—');
  y2 = labelVal(doc, col2, y2 + 2, 'Phone Number',  renter?.phone || '—');

  // vertical divider
  doc.setDrawColor(...SAND).setLineWidth(0.25);
  doc.line(margin + colW + 6, rowStart - 2, margin + colW + 6, Math.max(y1, y2) + 2);

  y = Math.max(y1, y2) + 6;
  hRule(doc, y);
  y += 8;

  /* ── SECTION 2: Property Details ────────────────────────────────────── */
  y = sectionHeader(doc, y, '2.  PROPERTY DETAILS');

  const durationDays = Math.max(
    1,
    Math.ceil((new Date(booking.endDate).getTime() - new Date(booking.startDate).getTime()) / (1000 * 60 * 60 * 24))
  );

  autoTable(doc, {
    startY: y,
    margin: { left: margin, right: margin },
    theme: 'plain',
    headStyles: {
      fillColor: LIGHT_GRN,
      textColor: FOREST,
      fontSize: 8.5,
      fontStyle: 'bold',
      cellPadding: { top: 3, bottom: 3, left: 4, right: 4 },
    },
    bodyStyles: {
      fontSize: 9,
      textColor: INK,
      cellPadding: { top: 3.5, bottom: 3.5, left: 4, right: 4 },
    },
    alternateRowStyles: { fillColor: [248, 246, 241] },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 55, textColor: SUB_TEXT, fontSize: 8 },
    },
    head: [['Field', 'Details']],
    body: [
      ['Garden / Orchard Name', orchard?.gardenName || '—'],
      ['Location',              orchard ? `${orchard.district}, ${orchard.state}, ${orchard.country || 'India'}` : '—'],
      ['Total Area',            orchard ? `${orchard.totalArea} ${orchard.areaUnit}` : '—'],
      ['Fruit Types',           orchard?.fruitTypes?.join(', ') || '—'],
      ['Total Trees',           orchard?.totalTrees ? String(orchard.totalTrees) : '—'],
      ['Expected Yield',        orchard?.expectedYield ? `${orchard.expectedYield} kg` : '—'],
    ],
  });

  y = (doc as any).lastAutoTable.finalY + 8;
  hRule(doc, y);
  y += 8;

  /* ── SECTION 3: Lease Terms ──────────────────────────────────────────── */
  y = sectionHeader(doc, y, '3.  LEASE TERMS');

  autoTable(doc, {
    startY: y,
    margin: { left: margin, right: margin },
    theme: 'plain',
    headStyles: {
      fillColor: LIGHT_GRN,
      textColor: FOREST,
      fontSize: 8.5,
      fontStyle: 'bold',
      cellPadding: { top: 3, bottom: 3, left: 4, right: 4 },
    },
    bodyStyles: {
      fontSize: 9,
      textColor: INK,
      cellPadding: { top: 3.5, bottom: 3.5, left: 4, right: 4 },
    },
    alternateRowStyles: { fillColor: [248, 246, 241] },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 55, textColor: SUB_TEXT, fontSize: 8 },
    },
    head: [['Field', 'Details']],
    body: [
      ['Lease Start Date',  formatDate(booking.startDate)],
      ['Lease End Date',    formatDate(booking.endDate)],
      ['Duration',          `${durationDays} day${durationDays !== 1 ? 's' : ''}`],
      ['Rent Type',         orchard?.rentType ? titleCase(orchard.rentType) : '—'],
      ['Booking Status',    titleCase(booking.bookingStatus)],
    ],
  });

  y = (doc as any).lastAutoTable.finalY + 8;
  hRule(doc, y);
  y += 8;

  /* ── SECTION 4: Financial Terms ─────────────────────────────────────── */
  y = sectionHeader(doc, y, '4.  FINANCIAL TERMS');

  autoTable(doc, {
    startY: y,
    margin: { left: margin, right: margin },
    theme: 'plain',
    headStyles: {
      fillColor: LIGHT_GRN,
      textColor: FOREST,
      fontSize: 8.5,
      fontStyle: 'bold',
      cellPadding: { top: 3, bottom: 3, left: 4, right: 4 },
    },
    bodyStyles: {
      fontSize: 9,
      textColor: INK,
      cellPadding: { top: 3.5, bottom: 3.5, left: 4, right: 4 },
    },
    alternateRowStyles: { fillColor: [248, 246, 241] },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 55, textColor: SUB_TEXT, fontSize: 8 },
      1: { fontStyle: 'bold' },
    },
    head: [['Field', 'Amount / Status']],
    body: [
      ['Base Price (Orchard)', orchard?.price ? formatCurrency(orchard.price) : '—'],
      ['Total Lease Amount',   formatCurrency(booking.totalAmount)],
      ['Payment Status',       titleCase(booking.paymentStatus)],
      ['Booking Reference',    booking._id],
      ['Agreement Date',       formatDate(booking.createdAt)],
    ],
  });

  y = (doc as any).lastAutoTable.finalY + 8;

  /* ── SECTION 5: Notes / Special Conditions (conditional) ───────────── */
  if (booking.message) {
    if (y + 30 > pageH - 20) {
      doc.addPage();
      doc.setFillColor(...CREAM_BG);
      doc.rect(0, 0, pageW, pageH, 'F');
      y = 20;
    }
    hRule(doc, y);
    y += 8;
    y = sectionHeader(doc, y, '5.  SPECIAL CONDITIONS / NOTES');

    doc.setFillColor(245, 243, 237);
    const msgLines = doc.splitTextToSize(booking.message, pageW - margin * 2 - 8);
    const boxH = msgLines.length * 5 + 10;
    doc.roundedRect(margin, y, pageW - margin * 2, boxH, 2, 2, 'F');
    doc.setFontSize(9).setFont('helvetica', 'normal').setTextColor(...INK);
    doc.text(msgLines, margin + 4, y + 6);
    y += boxH + 8;
  }

  /* ── SECTION 6: Signatures ──────────────────────────────────────────── */
  if (y + 45 > pageH - 20) {
    doc.addPage();
    doc.setFillColor(...CREAM_BG);
    doc.rect(0, 0, pageW, pageH, 'F');
    y = 20;
  }
  hRule(doc, y);
  y += 8;
  y = sectionHeader(doc, y, booking.message ? '6.  SIGNATURES' : '5.  SIGNATURES');

  const sigY = y + 8;
  const sigLineW = 65;

  // Owner signature block
  doc.setDrawColor(...INK).setLineWidth(0.4);
  doc.line(col1, sigY + 18, col1 + sigLineW, sigY + 18);
  doc.setFontSize(8).setFont('helvetica', 'bold').setTextColor(...INK);
  doc.text('Owner / Lessor', col1, sigY + 23);
  doc.setFontSize(7.5).setFont('helvetica', 'normal').setTextColor(...SUB_TEXT);
  doc.text(seller?.name || '—', col1, sigY + 28);
  doc.text('Date: ___________________', col1, sigY + 33);

  // Renter signature block
  doc.setDrawColor(...INK);
  doc.line(col2, sigY + 18, col2 + sigLineW, sigY + 18);
  doc.setFontSize(8).setFont('helvetica', 'bold').setTextColor(...INK);
  doc.text('Lessee / Renter', col2, sigY + 23);
  doc.setFontSize(7.5).setFont('helvetica', 'normal').setTextColor(...SUB_TEXT);
  doc.text(renter?.name || '—', col2, sigY + 28);
  doc.text('Date: ___________________', col2, sigY + 33);

  y = sigY + 40;

  /* ── disclaimer box ─────────────────────────────────────────────────── */
  if (y + 25 < pageH - 18) {
    y += 4;
    hRule(doc, y);
    y += 6;
    doc.setFillColor(240, 244, 238);
    doc.roundedRect(margin, y, pageW - margin * 2, 18, 2, 2, 'F');
    doc.setFontSize(7).setFont('helvetica', 'italic').setTextColor(...SUB_TEXT);
    const disclaimer =
      'This lease agreement has been auto-generated by OrchardLease upon booking confirmation. ' +
      'Both parties are advised to review all terms carefully. OrchardLease acts solely as a marketplace ' +
      'platform and is not a party to this agreement. This document should be reviewed by a legal professional ' +
      'before execution where required by applicable law.';
    const discLines = doc.splitTextToSize(disclaimer, pageW - margin * 2 - 8);
    doc.text(discLines, margin + 4, y + 5);
  }

  /* ── footers ────────────────────────────────────────────────────────── */
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addFooter(doc, i, totalPages);
  }

  /* ── save ───────────────────────────────────────────────────────────── */
  doc.save(`lease-agreement-${booking._id}.pdf`);
}
